# Generated by Django 4.2.24 on 2025-12-06 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_alter_tenant_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('refund', 'Refund'), ('discount', 'Discount'), ('cash_movement', 'Cash Movement'), ('inventory_adjustment', 'Inventory Adjustment'), ('shift_open', 'Shift Open'), ('shift_close', 'Shift Close'), ('settings_change', 'Settings Change'), ('security', 'Security Event'), ('export', 'Export'), ('import', 'Import')], db_index=True, max_length=50)),
                ('module', models.CharField(choices=[('sales', 'Sales'), ('inventory', 'Inventory'), ('products', 'Products'), ('customers', 'Customers'), ('payments', 'Payments'), ('shifts', 'Shifts'), ('cash', 'Cash Management'), ('settings', 'Settings'), ('users', 'Users'), ('auth', 'Authentication'), ('reports', 'Reports'), ('suppliers', 'Suppliers'), ('restaurant', 'Restaurant')], db_index=True, max_length=50)),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='activity_lo_tenant__f92502_idx'), models.Index(fields=['tenant', 'user', '-created_at'], name='activity_lo_tenant__37a4d3_idx'), models.Index(fields=['tenant', 'module', '-created_at'], name='activity_lo_tenant__91cb8d_idx'), models.Index(fields=['tenant', 'action', '-created_at'], name='activity_lo_tenant__a42df8_idx'), models.Index(fields=['tenant', 'resource_type', '-created_at'], name='activity_lo_tenant__e403d1_idx')],
            },
        ),
    ]
