# Generated by Django 4.2.7 on 2026-01-20 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0005_alter_printer_options'),
        ('products', '0014_rename_products_pr_outlet_idx_products_pr_outlet__655c0b_idx_and_more'),
        ('inventory', '0004_add_batch_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='batch',
            name='unique_batch_variation_outlet',
        ),
        migrations.RenameIndex(
            model_name='batch',
            new_name='inventory_b_tenant__9caa42_idx',
            old_name='inventory_b_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='batch',
            new_name='inventory_b_variati_ea7ea7_idx',
            old_name='inventory_b_var_outlet_idx',
        ),
        migrations.RenameIndex(
            model_name='batch',
            new_name='inventory_b_expiry__96c551_idx',
            old_name='inventory_b_expiry_idx',
        ),
        migrations.RenameIndex(
            model_name='batch',
            new_name='inventory_b_variati_1eecd5_idx',
            old_name='inventory_b_var_out_exp_idx',
        ),
        migrations.AlterField(
            model_name='locationstock',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Current stock quantity at this location (legacy - prefer using get_available_quantity())', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('variation', 'outlet', 'batch_number')},
        ),
    ]
