# Generated by Django 4.2.24 on 2025-12-07 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0003_alter_tenant_type'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_sale_notifications', models.BooleanField(default=True)),
                ('enable_stock_notifications', models.BooleanField(default=True)),
                ('enable_staff_notifications', models.BooleanField(default=True)),
                ('enable_system_notifications', models.BooleanField(default=True)),
                ('enable_payment_notifications', models.BooleanField(default=True)),
                ('enable_customer_notifications', models.BooleanField(default=True)),
                ('enable_report_notifications', models.BooleanField(default=True)),
                ('enable_low_priority', models.BooleanField(default=True)),
                ('enable_normal_priority', models.BooleanField(default=True)),
                ('enable_high_priority', models.BooleanField(default=True)),
                ('enable_urgent_priority', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_tenant__27d8a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_tenant__8cf297_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_tenant__76973e_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_created_e4c995_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_by',
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Frontend link to view details of the notification', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='resource_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID of the resource related to the notification', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='resource_type',
            field=models.CharField(blank=True, help_text="e.g., 'Sale', 'Product', 'Shift'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('sale', 'Sale'), ('stock', 'Stock'), ('staff', 'Staff'), ('system', 'System'), ('payment', 'Payment'), ('customer', 'Customer'), ('report', 'Report')], db_index=True, default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User to whom the notification is directed (if specific)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'read', '-created_at'], name='notificatio_tenant__2f8cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', '-created_at'], name='notificatio_user_id_cba35e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', '-created_at'], name='notificatio_type_d2e2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', '-created_at'], name='notificatio_priorit_b3d0b6_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'tenant')},
        ),
    ]
