# Generated by Django 4.2.24 on 2025-11-24 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlets', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('can_sales', models.BooleanField(default=False)),
                ('can_inventory', models.BooleanField(default=False)),
                ('can_products', models.BooleanField(default=False)),
                ('can_customers', models.BooleanField(default=False)),
                ('can_reports', models.BooleanField(default=False)),
                ('can_staff', models.BooleanField(default=False)),
                ('can_settings', models.BooleanField(default=False)),
                ('can_dashboard', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'staff_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlets', models.ManyToManyField(blank=True, related_name='staff_members', to='outlets.outlet')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='staff.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'db_table': 'staff_staff',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='outlets.outlet')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'staff_attendance',
                'ordering': ['-check_in'],
            },
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['tenant'], name='staff_staff_tenant__b387e6_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['role'], name='staff_staff_role_id_d32aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['tenant'], name='staff_role_tenant__59ad02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['staff'], name='staff_atten_staff_i_9c9d22_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['outlet'], name='staff_atten_outlet__f036c6_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['check_in'], name='staff_atten_check_i_b0b4f5_idx'),
        ),
    ]
