# Generated by Django 4.2.24 on 2025-12-11 20:41

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_alter_tenant_type'),
        ('outlets', '0003_delete_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Supplies', 'Supplies'), ('Utilities', 'Utilities'), ('Rent', 'Rent'), ('Marketing', 'Marketing'), ('Travel', 'Travel'), ('Equipment', 'Equipment'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], max_length=50)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('other', 'Other')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('expense_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='outlets.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tenants.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses_expense',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant'], name='expenses_ex_tenant__6d198a_idx'), models.Index(fields=['outlet'], name='expenses_ex_outlet__49f467_idx'), models.Index(fields=['expense_date'], name='expenses_ex_expense_cf8a73_idx'), models.Index(fields=['status'], name='expenses_ex_status_cbb790_idx'), models.Index(fields=['category'], name='expenses_ex_categor_fcaba7_idx')],
            },
        ),
    ]
