# Generated by Django 4.2.24 on 2025-11-24 17:49

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_date', models.DateField()),
                ('opening_cash_balance', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('floating_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('closing_cash_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='outlets.outlet')),
                ('till', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='outlets.till')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'db_table': 'shifts_shift',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['outlet'], name='shifts_shif_outlet__7b4605_idx'), models.Index(fields=['till'], name='shifts_shif_till_id_3250cd_idx'), models.Index(fields=['user'], name='shifts_shif_user_id_2bb1a0_idx'), models.Index(fields=['operating_date'], name='shifts_shif_operati_aac5e8_idx'), models.Index(fields=['status'], name='shifts_shif_status_8c03df_idx')],
                'unique_together': {('outlet', 'till', 'operating_date', 'status')},
            },
        ),
    ]
