# Generated by Django 4.2.7 on 2025-12-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='device_id',
            field=models.CharField(blank=True, help_text='Device identifier for multi-device tracking', max_length=255),
        ),
        migrations.AddField(
            model_name='shift',
            name='sync_status',
            field=models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('conflict', 'Conflict')], default='synced', max_length=20),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['device_id'], name='shifts_shif_device__4be374_idx'),
        ),
    ]
