"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Checkbox } from "@/components/ui/checkbox"
import { Eye, Upload } from "lucide-react"
import { useEffect, useState } from "react"
import { useToast } from "@/components/ui/use-toast"
import { useBusinessStore } from "@/stores/businessStore"
import { api } from "@/lib/api"
import { ReceiptTemplateList } from "./receipt-template-list"
import { ReceiptTemplateEditor } from "./receipt-template-editor"
import { ReceiptTemplatePreview } from "./receipt-template-preview"

export function ReceiptTemplateTab() {
  const { toast } = useToast()

  // Square-style principle: Templates are editable UI artifacts; generated receipts
  // are immutable legal records generated by the backend. The settings page
  // should never allow editing of stored receipt content nor trigger live printing.
  const [isSaving, setIsSaving] = useState(false)
  const [showPreview, setShowPreview] = useState(false)
  const [includeLogo, setIncludeLogo] = useState(true)
  const [templates, setTemplates] = useState<any[]>([])
  const [selectedTemplateId, setSelectedTemplateId] = useState<string | null>(null)
  const [templateName, setTemplateName] = useState<string>("Default Template")
  const [templateFormat, setTemplateFormat] = useState<string>("text")
  const [templateContent, setTemplateContent] = useState<string>("")
  const [templateDefault, setTemplateDefault] = useState<boolean>(true)
  const { currentOutlet, currentBusiness } = useBusinessStore()

  // Keep local state minimal in Settings UI — templates are editable. Receipts
  // are immutable legal records and must not be edited from settings.
  const handleSave = async () => {
    if (!currentOutlet) {
      toast({ title: 'No outlet selected', description: 'Please select an outlet before saving a template.', variant: 'destructive' })
      return
    }
    setIsSaving(true)
    try {
      const payload = {
        name: templateName,
        format: templateFormat,
        content: templateContent,
        is_default: templateDefault,
      }

      if (selectedTemplateId) {
        await api.patch(`/receipt-templates/${selectedTemplateId}/`, payload)
      } else {
        await api.post(`/receipt-templates/`, payload)
      }

      // Refresh list
      await loadTemplates()

      toast({ title: 'Saved', description: 'Receipt template saved.' })
    } catch (err: any) {
      console.error('Save template failed', err)
      toast({ title: 'Save failed', description: err?.message || 'Unable to save template', variant: 'destructive' })
    } finally {
      setIsSaving(false)
    }
  }

  const loadTemplates = async () => {
    try {
      const res = await api.get<any>(`/receipt-templates/?page=1`)
      const data = Array.isArray(res) ? res : (res.results || [])
      setTemplates(data)
      if (data.length > 0) {
        const def = data.find((t: any) => t.is_default) || data[0]
        setSelectedTemplateId(String(def.id))
        setTemplateName(def.name || 'Default Template')
        setTemplateFormat(def.format || 'text')
        setTemplateContent(def.content || '')
        setTemplateDefault(Boolean(def.is_default))
      }
    } catch (err) {
      console.error('Load templates failed', err)
    }
  }

  useEffect(() => {
    loadTemplates()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentOutlet])

  return (
    <Card>
      <CardHeader>
        <CardTitle>Receipt Template</CardTitle>
        <CardDescription>Customize your receipt layout and content</CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="space-y-2">
          <div className="flex items-center space-x-2">
            <Checkbox
              id="include-logo"
              checked={includeLogo}
              onCheckedChange={(checked) => setIncludeLogo(checked as boolean)}
            />
            <Label htmlFor="include-logo" className="cursor-pointer">
              Include Business Logo
            </Label>
          </div>
          {includeLogo && (
            <div className="ml-6 space-y-2">
              <div className="flex items-center gap-4">
                <div className="w-24 h-24 rounded-lg border-2 border-dashed flex items-center justify-center bg-muted">
                  <Upload className="h-8 w-8 text-muted-foreground" />
                </div>
                <Button variant="outline" size="sm">
                  <Upload className="mr-2 h-4 w-4" />
                  Upload Logo
                </Button>
              </div>
            </div>
          )}
        </div>

        <div className="space-y-2">
          <Label htmlFor="template-select">Saved Templates</Label>
          <div className="flex items-center gap-2">
            <select
              id="template-select"
              value={selectedTemplateId || ''}
              onChange={(e) => {
                const id = e.target.value || null
                setSelectedTemplateId(id)
                const t = templates.find((x: any) => String(x.id) === id)
                if (t) {
                  setTemplateName(t.name || 'Default Template')
                  setTemplateFormat(t.format || 'text')
                  setTemplateContent(t.content || '')
                  setTemplateDefault(Boolean(t.is_default))
                } else {
                  // reset
                  setTemplateName('Default Template')
                  setTemplateFormat('text')
                  setTemplateContent('')
                  setTemplateDefault(true)
                }
              }}
              className="rounded-md border px-2 py-1"
            >
              <option value="">-- New Template --</option>
              {templates.map((t) => (
                <option key={t.id} value={String(t.id)}>{t.name}</option>
              ))}
            </select>
            {selectedTemplateId && (
              <Button variant="destructive" size="sm" onClick={async () => {
                try {
                  await api.delete(`/receipt-templates/${selectedTemplateId}/`)
                  toast({ title: 'Deleted', description: 'Template deleted.' })
                  await loadTemplates()
                } catch (err: any) {
                  console.error('Delete failed', err)
                  toast({ title: 'Delete failed', description: err?.message || 'Unable to delete template', variant: 'destructive' })
                }
              }}>Delete</Button>
            )}
          </div>

          <div className="mt-3">
            <Label htmlFor="header-text">Template Name</Label>
            <Input id="header-text" value={templateName} onChange={(e) => setTemplateName(e.target.value)} />
          </div>
        </div>

        <div className="grid grid-cols-2 gap-6">
          <div>
            <ReceiptTemplateList
              templates={templates}
              selectedId={selectedTemplateId}
              onSelect={(id: any) => {
                setSelectedTemplateId(id)
                const t = templates.find((x: any) => String(x.id) === id)
                if (t) {
                  setTemplateName(t.name || 'Default Template')
                  setTemplateFormat(t.format || 'text')
                  setTemplateContent(t.content || '')
                  setTemplateDefault(Boolean(t.is_default))
                } else {
                  setTemplateName('Default Template')
                  setTemplateFormat('text')
                  setTemplateContent('')
                  setTemplateDefault(true)
                }
              }}
              onDelete={async () => await loadTemplates()}
            />

            <div className="mt-4">
              <ReceiptTemplateEditor
                template={templates.find((x:any) => String(x.id) === selectedTemplateId) || null}
                onSaved={async () => await loadTemplates()}
              />
            </div>
          </div>

          <div>
            <ReceiptTemplatePreview templateId={selectedTemplateId} />
          </div>
        </div>

        <div className="space-y-2">
          <Label htmlFor="receipt-width">Receipt Width (mm)</Label>
          <Input id="receipt-width" type="number" defaultValue="80" />
        </div>

        <div className="flex gap-2">
          <Button variant="outline" onClick={() => setShowPreview(true)}>
            <Eye className="mr-2 h-4 w-4" />
            Preview Receipt
          </Button>

          <Button onClick={handleSave} disabled={isSaving}>
            {isSaving ? "Saving..." : "Save Changes"}
          </Button>
        </div>
      </CardContent>
      

    </Card>
  )
}


