# Generated by Django 4.2.24 on 2025-12-07 07:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_type'),
        ('products', '0008_create_default_variations'),
        ('suppliers', '0004_add_variation_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPurchaseOrderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_po_enabled', models.BooleanField(default=False, help_text='Enable automatic purchase order creation when low stock is detected')),
                ('default_reorder_quantity', models.IntegerField(default=10, help_text='Default quantity to reorder if not specified in ProductSupplier', validators=[django.core.validators.MinValueValidator(1)])),
                ('auto_approve_po', models.BooleanField(default=False, help_text='Automatically approve auto-generated purchase orders')),
                ('notify_on_auto_po', models.BooleanField(default=True, help_text='Send notifications when auto-POs are created')),
                ('notification_emails', models.TextField(blank=True, help_text='Comma-separated email addresses to notify (optional)')),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Minimum order value to create PO (0 = no minimum)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('group_by_supplier', models.BooleanField(default=True, help_text='Group low stock items by supplier when creating auto-POs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(help_text='One settings record per tenant', on_delete=django.db.models.deletion.CASCADE, related_name='auto_po_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Auto Purchase Order Settings',
                'verbose_name_plural': 'Auto Purchase Order Settings',
                'db_table': 'suppliers_autopurchaseordersettings',
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reorder_quantity', models.IntegerField(default=0, help_text='Quantity to reorder when low stock is detected', validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_point', models.IntegerField(default=0, help_text="Stock level at which to trigger reorder (if 0, uses product's low_stock_threshold)", validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit from this supplier (if different from product cost)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_preferred', models.BooleanField(default=False, help_text='Preferred supplier for this product (used for auto-PO creation)')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_suppliers', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_suppliers', to='suppliers.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_suppliers', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Product Supplier',
                'verbose_name_plural': 'Product Suppliers',
                'db_table': 'suppliers_productsupplier',
                'indexes': [models.Index(fields=['tenant'], name='suppliers_p_tenant__8bfce6_idx'), models.Index(fields=['product'], name='suppliers_p_product_1b70eb_idx'), models.Index(fields=['supplier'], name='suppliers_p_supplie_6ef77f_idx'), models.Index(fields=['is_preferred'], name='suppliers_p_is_pref_86f58b_idx'), models.Index(fields=['is_active'], name='suppliers_p_is_acti_88f16e_idx')],
                'unique_together': {('product', 'supplier')},
            },
        ),
    ]
