# Generated by Django 4.2.24 on 2025-12-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_make_sku_optional'),
        ('outlets', '0003_delete_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('out_of_service', 'Out of Service')], default='available', max_length=20)),
                ('location', models.CharField(blank=True, help_text='e.g., Main Dining, Patio, VIP', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_tables', to='outlets.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_tables', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Restaurant Table',
                'verbose_name_plural': 'Restaurant Tables',
                'db_table': 'restaurant_table',
                'ordering': ['number'],
                'indexes': [models.Index(fields=['tenant'], name='restaurant__tenant__c29416_idx'), models.Index(fields=['outlet'], name='restaurant__outlet__406eb0_idx'), models.Index(fields=['status'], name='restaurant__status_8e113d_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
