# Generated by Django 4.2.24 on 2025-12-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_amount_paid_sale_due_date_sale_payment_status_and_more'),
        ('tenants', '0002_make_sku_optional'),
        ('outlets', '0003_delete_table'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenOrderTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kot_number', models.CharField(db_index=True, help_text='Kitchen Order Ticket number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('sent_to_kitchen_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='outlets.outlet')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='sales.sale')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_orders', to='restaurant.table')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Kitchen Order Ticket',
                'verbose_name_plural': 'Kitchen Order Tickets',
                'db_table': 'restaurant_kitchenorderticket',
                'ordering': ['-sent_to_kitchen_at'],
                'indexes': [models.Index(fields=['tenant'], name='restaurant__tenant__ca967f_idx'), models.Index(fields=['outlet'], name='restaurant__outlet__cba3e4_idx'), models.Index(fields=['sale'], name='restaurant__sale_id_a7226c_idx'), models.Index(fields=['table'], name='restaurant__table_i_16d8e8_idx'), models.Index(fields=['status'], name='restaurant__status_8a9f72_idx'), models.Index(fields=['sent_to_kitchen_at'], name='restaurant__sent_to_f57cf7_idx')],
            },
        ),
    ]
