# Generated by Django 4.2.24 on 2025-12-01 03:25

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_amount_paid_sale_due_date_sale_payment_status_and_more'),
        ('tenants', '0002_make_sku_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_enabled',
            field=models.BooleanField(default=False, help_text='Whether this customer can make credit purchases'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Maximum credit limit for this customer', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_notes',
            field=models.TextField(blank=True, help_text="Notes about customer's credit account"),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', help_text='Current credit account status', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms_days',
            field=models.IntegerField(default=30, help_text='Payment terms in days (e.g., 30 for Net 30, 60 for Net 60)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], default='cash', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Date payment was recorded')),
                ('reference_number', models.CharField(blank=True, help_text='Receipt number, check number, or other reference', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_payments', to='customers.customer')),
                ('sale', models.ForeignKey(help_text='The invoice being paid', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_payments', to='tenants.tenant')),
                ('user', models.ForeignKey(help_text='User who recorded the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Payment',
                'verbose_name_plural': 'Credit Payments',
                'db_table': 'customers_creditpayment',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant'], name='customers_c_tenant__ab8b83_idx'), models.Index(fields=['customer'], name='customers_c_custome_e62dcc_idx'), models.Index(fields=['sale'], name='customers_c_sale_id_4b0a7b_idx'), models.Index(fields=['payment_date'], name='customers_c_payment_3e8f25_idx')],
            },
        ),
    ]
