# Generated by Django 4.2.24 on 2025-11-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='currency_symbol',
            field=models.CharField(default='MK', max_length=10),
        ),
    ]
