# Generated by Django 4.2.24 on 2025-12-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_make_sku_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[('retail', 'Wholesale and Retail'), ('restaurant', 'Restaurant'), ('bar', 'Bar')], default='retail', max_length=20),
        ),
    ]
