# Generated by Django 4.2.24 on 2025-12-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='pos_type',
            field=models.CharField(choices=[('standard', 'Standard POS'), ('single_product', 'Single-Product POS')], default='standard', max_length=20),
        ),
    ]
