# Generated by Django 4.2.24 on 2026-01-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_pos_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Business logo', null=True, upload_to='tenants/logos/'),
        ),
    ]
