# Generated by Django 4.2.24 on 2025-11-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_make_sku_optional'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        # Removed unique_together constraint - SKU uniqueness is enforced in serializer
        # unique_together doesn't work well with blank values
    ]
