# Generated by Django 4.2.24 on 2025-11-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_make_sku_optional'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),  # Remove unique_together constraint
        ),
    ]
