# Generated by Django 4.2.24 on 2025-12-03 15:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_sku_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_wholesale_quantity',
            field=models.IntegerField(default=1, help_text='Minimum quantity required for wholesale pricing', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_enabled',
            field=models.BooleanField(default=False, help_text='Whether this product is available for wholesale'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wholesale price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Retail price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
