# Generated by Django 4.2.24 on 2025-12-04 00:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_price_to_retail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
