# Generated by Django 4.2.24 on 2025-12-06 20:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Variation name (e.g., 'Bottle', 'Shot', '500ml', 'Large')", max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price for this variation', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost price for this variation (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('sku', models.CharField(blank=True, db_index=True, help_text='SKU for this variation (unique per product)', max_length=100)),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='Barcode for this variation', max_length=100)),
                ('track_inventory', models.BooleanField(default=True, help_text='Whether to track inventory for this variation')),
                ('unit', models.CharField(default='pcs', help_text='Unit of measurement (pcs, ml, kg, l, g, box, pack)', max_length=50)),
                ('low_stock_threshold', models.IntegerField(default=0, help_text='Low stock alert threshold for this variation', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this variation is active')),
                ('sort_order', models.IntegerField(default=0, help_text='Sort order for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product')),
            ],
            options={
                'verbose_name': 'Item Variation',
                'verbose_name_plural': 'Item Variations',
                'db_table': 'products_itemvariation',
                'ordering': ['sort_order', 'name', 'id'],
                'indexes': [models.Index(fields=['product'], name='products_it_product_67e04b_idx'), models.Index(fields=['product', 'is_active'], name='products_it_product_e353fb_idx'), models.Index(fields=['sku'], name='products_it_sku_78108b_idx'), models.Index(fields=['barcode'], name='products_it_barcode_4ed9d0_idx'), models.Index(fields=['track_inventory'], name='products_it_track_i_89b204_idx')],
                'unique_together': {('product', 'sku')},
            },
        ),
    ]
