# Generated by Django 4.2.24 on 2025-12-09 09:24

from django.db import migrations, models


def convert_empty_sku_to_null(apps, schema_editor):
    """Convert empty string SKUs to NULL"""
    Product = apps.get_model('products', 'Product')
    ItemVariation = apps.get_model('products', 'ItemVariation')
    
    # Convert empty strings to NULL for products
    Product.objects.filter(sku='').update(sku=None)
    
    # Convert empty strings to NULL for variations
    ItemVariation.objects.filter(sku='').update(sku=None)


def reverse_convert_null_to_empty(apps, schema_editor):
    """Reverse: Convert NULL SKUs to empty strings"""
    Product = apps.get_model('products', 'Product')
    ItemVariation = apps.get_model('products', 'ItemVariation')
    
    # Convert NULL to empty strings for products
    Product.objects.filter(sku__isnull=True).update(sku='')
    
    # Convert NULL to empty strings for variations
    ItemVariation.objects.filter(sku__isnull=True).update(sku='')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_create_default_variations'),
    ]

    operations = [
        # Step 1: Remove unique constraint if it exists (must be done before altering column)
        # Drop constraint first (which will also drop the index)
        migrations.RunSQL(
            sql="ALTER TABLE products_product DROP CONSTRAINT IF EXISTS products_product_tenant_id_sku_5846d4a0_uniq;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        
        # Step 2: Alter the fields to allow NULL first
        migrations.AlterField(
            model_name='itemvariation',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='SKU for this variation (unique per product)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        
        # Step 3: Now convert empty strings to NULL (after column allows NULL)
        migrations.RunPython(convert_empty_sku_to_null, reverse_convert_null_to_empty),
    ]
