# Generated by Django migration
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_make_outlet_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(help_text="Unit name (e.g., 'piece', 'half-dozen', 'dozen', 'box')", max_length=50)),
                ('conversion_factor', models.DecimalField(decimal_places=4, help_text='How many base units this unit equals (e.g., 12 for dozen if base is piece)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('retail_price', models.DecimalField(decimal_places=2, help_text='Retail price for this unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Wholesale price for this unit (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this unit is available for sale')),
                ('sort_order', models.IntegerField(default=0, help_text='Sort order for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Product this unit belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='selling_units', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Unit',
                'verbose_name_plural': 'Product Units',
                'db_table': 'products_productunit',
                'ordering': ['sort_order', 'unit_name', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['product'], name='products_pr_product_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['product', 'is_active'], name='products_pr_product_active_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['unit_name'], name='products_pr_unit_name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productunit',
            unique_together={('product', 'unit_name')},
        ),
    ]

