# Generated by Django 4.2.7 on 2025-12-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_add_product_unit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_outlet__655c0b_idx',
            old_name='products_pr_outlet_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_tenant__dd3e97_idx',
            old_name='products_pr_tenant_outlet_idx',
        ),
        migrations.RenameIndex(
            model_name='productunit',
            new_name='products_pr_product_2bcfe0_idx',
            old_name='products_pr_product_idx',
        ),
        migrations.RenameIndex(
            model_name='productunit',
            new_name='products_pr_product_63b8b4_idx',
            old_name='products_pr_product_active_idx',
        ),
        migrations.RenameIndex(
            model_name='productunit',
            new_name='products_pr_unit_na_ab0b33_idx',
            old_name='products_pr_unit_name_idx',
        ),
    ]
