# Generated by Django 4.2.24 on 2025-12-01 03:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount paid towards this sale (for credit sales)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='sale',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Payment due date for credit sales', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='paid', help_text='Payment status for credit sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile Money'), ('tab', 'Tab'), ('credit', 'Credit')], default='cash', max_length=20),
        ),
    ]
