# Generated by Django 4.2.24 on 2025-12-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_kitchenorderticket'),
        ('sales', '0002_sale_amount_paid_sale_due_date_sale_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='guests',
            field=models.PositiveIntegerField(blank=True, help_text='Number of guests at table', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Order priority for kitchen', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='table',
            field=models.ForeignKey(blank=True, help_text='Table for restaurant orders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurant.table'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='kitchen_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('cancelled', 'Cancelled')], default='pending', help_text='Kitchen preparation status', max_length=20),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Special instructions or modifiers for kitchen'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='prepared_at',
            field=models.DateTimeField(blank=True, help_text='When item was marked as ready', null=True),
        ),
    ]
