# Generated by Django 4.2.24 on 2025-12-04 15:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_guests_sale_priority_sale_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash_received',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cash amount received from customer (for cash payments)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='sale',
            name='change_given',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Change given to customer (cash_received - total)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
