# Generated by Django 4.2.24 on 2025-12-06 08:27

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0003_delete_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0003_alter_tenant_type'),
        ('customers', '0002_customer_credit_enabled_customer_credit_limit_and_more'),
        ('sales', '0004_sale_cash_received_sale_change_given'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(db_index=True, help_text='Unique delivery reference number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready for Dispatch'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Delivery Failed')], default='pending', max_length=20)),
                ('delivery_method', models.CharField(choices=[('own_vehicle', 'Own Vehicle'), ('third_party', 'Third Party Courier'), ('customer_pickup', 'Customer Pickup'), ('external_shipping', 'External Shipping Company')], default='own_vehicle', max_length=20)),
                ('delivery_address', models.TextField(help_text='Full delivery address')),
                ('delivery_city', models.CharField(blank=True, max_length=100)),
                ('delivery_state', models.CharField(blank=True, max_length=100)),
                ('delivery_postal_code', models.CharField(blank=True, max_length=20)),
                ('delivery_country', models.CharField(blank=True, max_length=100)),
                ('delivery_contact_name', models.CharField(blank=True, help_text='Contact person at delivery address', max_length=255)),
                ('delivery_contact_phone', models.CharField(blank=True, max_length=20)),
                ('scheduled_date', models.DateField(blank=True, help_text='Scheduled delivery date', null=True)),
                ('scheduled_time_start', models.TimeField(blank=True, help_text='Scheduled delivery time window start', null=True)),
                ('scheduled_time_end', models.TimeField(blank=True, help_text='Scheduled delivery time window end', null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, help_text='Actual delivery date/time', null=True)),
                ('courier_name', models.CharField(blank=True, help_text='Name of courier/shipping company', max_length=255)),
                ('tracking_number', models.CharField(blank=True, help_text='Tracking number for third-party shipping', max_length=100)),
                ('driver_name', models.CharField(blank=True, help_text='Driver name for own vehicle deliveries', max_length=255)),
                ('vehicle_number', models.CharField(blank=True, help_text='Vehicle registration number', max_length=50)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Delivery fee charged to customer', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Actual shipping cost (for cost tracking)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True, help_text='Internal notes about delivery')),
                ('customer_notes', models.TextField(blank=True, help_text='Notes visible to customer')),
                ('delivery_instructions', models.TextField(blank=True, help_text='Special delivery instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User responsible for delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deliveries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='customers.customer')),
                ('delivered_by', models.ForeignKey(blank=True, help_text='User who completed delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_deliveries', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(help_text='Outlet dispatching the delivery', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='outlets.outlet')),
                ('sale', models.ForeignKey(help_text='The sale this delivery fulfills', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='sales.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'db_table': 'sales_delivery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='sales.delivery')),
            ],
            options={
                'verbose_name': 'Delivery Status History',
                'verbose_name_plural': 'Delivery Status Histories',
                'db_table': 'sales_deliverystatushistory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity being delivered in this delivery', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_delivered', models.BooleanField(default=False, help_text='Whether this item was successfully delivered')),
                ('delivered_quantity', models.IntegerField(default=0, help_text='Actual quantity delivered (may differ from ordered)')),
                ('notes', models.TextField(blank=True, help_text='Notes specific to this item delivery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='sales.delivery')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='sales.saleitem')),
            ],
            options={
                'verbose_name': 'Delivery Item',
                'verbose_name_plural': 'Delivery Items',
                'db_table': 'sales_deliveryitem',
                'unique_together': {('delivery', 'sale_item')},
            },
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['tenant'], name='sales_deliv_tenant__3ac99f_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['sale'], name='sales_deliv_sale_id_c9d233_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['customer'], name='sales_deliv_custome_4dc4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status'], name='sales_deliv_status_a10cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['scheduled_date'], name='sales_deliv_schedul_b6bfc1_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivery_number'], name='sales_deliv_deliver_e0449b_idx'),
        ),
    ]
