# Generated by Django 4.2.7 on 2025-12-09 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_add_unit_to_sale_item'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='saleitem',
            new_name='sales_salei_unit_id_0fb8f8_idx',
            old_name='sales_saleit_unit_idx',
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(help_text='Quantity sold in the selected unit', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
