# Generated by Django 4.2.24 on 2025-12-15 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0003_alter_tenant_type'),
        ('sales', '0008_rename_sales_saleit_unit_idx_sales_salei_unit_id_0fb8f8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, help_text='Receipt number for quick lookup', max_length=50, unique=True)),
                ('format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('json', 'JSON')], default='html', help_text='Format of stored receipt', max_length=10)),
                ('content', models.TextField(help_text='Receipt content (HTML/JSON)')),
                ('pdf_file', models.FileField(blank=True, help_text='PDF file if format is PDF', null=True, upload_to='receipts/pdf/')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When receipt was generated')),
                ('is_sent', models.BooleanField(default=False, help_text='Whether receipt was sent to customer')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When receipt was sent', null=True)),
                ('sent_via', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('print', 'Print'), ('none', 'Not Sent')], default='none', help_text='Method used to send receipt', max_length=20)),
                ('access_count', models.IntegerField(default=0, help_text='Number of times receipt was accessed')),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='Last time receipt was accessed', null=True)),
                ('generated_by', models.ForeignKey(help_text='User who created the sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_receipts', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(help_text='The sale this receipt belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='sales.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'db_table': 'sales_receipt',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['tenant'], name='sales_recei_tenant__635fea_idx'), models.Index(fields=['sale'], name='sales_recei_sale_id_1567f1_idx'), models.Index(fields=['receipt_number'], name='sales_recei_receipt_0e369b_idx'), models.Index(fields=['generated_at'], name='sales_recei_generat_9847c4_idx')],
            },
        ),
    ]
