# Generated by Django 4.2.7 on 2026-01-10 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_refactor_receipt'),
        ('sales', '0009_receipt'),
    ]

    operations = [
    ]
