# Generated by Django 4.2.7 on 2026-01-19 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_pos_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0010_merge_0008_refactor_receipt_0009_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Template', max_length=100)),
                ('format', models.CharField(choices=[('text', 'Plain Text'), ('html', 'HTML'), ('json', 'JSON')], default='text', max_length=10)),
                ('content', models.TextField(blank=True, help_text='Template content (text/html/json)')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_templates', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Receipt Template',
                'verbose_name_plural': 'Receipt Templates',
                'db_table': 'sales_receipttemplate',
                'ordering': ['-is_default', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='deliveryitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='deliveryitem',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='deliveryitem',
            name='sale_item',
        ),
        migrations.RemoveField(
            model_name='deliverystatushistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='deliverystatushistory',
            name='delivery',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='content',
            field=models.TextField(help_text='Receipt content (HTML/JSON/ESC/POS base64)'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='format',
            field=models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('json', 'JSON'), ('escpos', 'ESC/POS')], default='json', help_text='Format of stored receipt', max_length=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='generated_by',
            field=models.ForeignKey(help_text='User who created the receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='sale',
            field=models.ForeignKey(help_text='The sale this receipt belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='If superseded, reference to the new receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='sales.receipt'),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryItem',
        ),
        migrations.DeleteModel(
            name='DeliveryStatusHistory',
        ),
    ]
