# Generated by Django 4.2.24 on 2025-11-24 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Outlet',
                'verbose_name_plural': 'Outlets',
                'db_table': 'outlets_outlet',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Till',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_in_use', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tills', to='outlets.outlet')),
            ],
            options={
                'verbose_name': 'Till',
                'verbose_name_plural': 'Tills',
                'db_table': 'outlets_till',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['outlet'], name='outlets_til_outlet__dea4c6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='outlet',
            index=models.Index(fields=['tenant'], name='outlets_out_tenant__7164da_idx'),
        ),
    ]
