# Generated by Django 4.2.24 on 2025-12-02 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0002_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
