# Generated by Django 4.2.7 on 2026-01-09 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0003_delete_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=512)),
                ('driver', models.CharField(choices=[('qz', 'QZ Tray'), ('network', 'Network/TCP'), ('bluetooth', 'Bluetooth'), ('other', 'Other')], default='qz', max_length=32)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='outlets.outlet')),
            ],
            options={
                'verbose_name': 'Printer',
                'verbose_name_plural': 'Printers',
                'db_table': 'outlets_printer',
                'indexes': [models.Index(fields=['outlet'], name='outlets_pri_outlet__4578eb_idx'), models.Index(fields=['identifier'], name='outlets_pri_identif_37f530_idx')],
                'unique_together': {('outlet', 'identifier')},
            },
        ),
    ]
