# Generated by Django 4.2.7 on 2026-01-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0004_printer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': 'Printer', 'verbose_name_plural': 'Printers'},
        ),
    ]
